language: python
python: 3.5
cache: pip
fast_finish: true

branches:
  only:
  - develop
  - staging
  - prod

before_install:
  - openssl aes-256-cbc -K $encrypted_1b7d91bd2a09_key -iv $encrypted_1b7d91bd2a09_iv -in agora-access.pem.enc -out ~/.ssh/agora-access.pem -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/agora-access.pem
  - echo -e "Host $BASTIAN_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ~/.ssh/agora-access.pem

script:
  - ./updatedb.sh || travis_terminate 1
