language: python
python: 3.5
cache: pip
fast_finish: true

branches:
  only:
  - develop
  - staging
  - prod

matrix:
  fast_finish: true

branches:
  only:
  - develop
  - staging
  - prod

before_install:
  - openssl aes-256-cbc -K $encrypted_7dd696d233c6_key -iv $encrypted_7dd696d233c6_iv -in toptal_org-sagebase-scicomp.pem.enc -out ~\/.ssh/toptal_org-sagebase-scicomp.pem -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./toptal_org-sagebase-scicomp.pem
  - echo -e "Host $BASTIAN_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./toptal_org-sagebase-scicomp.pem

install:
  - sudo apt-get install -y build-essential libssl-dev
  - sudo pip install synapseclient[pandas,pysftp]

stages:
  - name: get-data
  - name: import-data

jobs:
  include:
    - stage: get-data
      script:
        - ./get-data.sh || travis_terminate 1
    - stage: import-data
      script:
        - ./import-data.sh || travis_terminate 1
