name: main

on:
  push:
    branches: [ 'develop','staging','prod' ]

jobs:
  deploy:
    # self hosted runner labels are setup in github to match branch names
    runs-on: [self-hosted, ${{ github.ref_name }}]
    # variables in context environments are setup in github to match branch names
    environment:
      name: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            synapseclient[pandas,pysftp]
      - name: Setup mongo tools - mongo-tools and mongo-shell
        uses: boly38/action-mongo-tools@stable
      - name: Import Synapse Data
        run: ./import-data.sh $BRANCH $SYNAPSE_USERNAME $SYNAPSE_PASSWORD $DB_HOST $DB_USER $DB_PASS
        env:
          BRANCH: ${{ github.ref_name }}
          SYNAPSE_USERNAME: ${{ secrets.SYNAPSE_USERNAME }}
          SYNAPSE_PASSWORD: ${{ secrets.SYNAPSE_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
